### ISSUE TITLE
Unstable formatting on multi-line dollar-quoted strings with `sql-formatter` `dialect` option

### ISSUE THREAD

**Issue by karlhorky** [Sec-ant/prettier-plugin-embed#45] opened 2023-12-03 18:15 UTC
Hi @Sec-ant, hope things are going well 👋 

When [patching `prettier-plugin-sql` to add the `sql-formatter` `dialect` option](https://github.com/un-ts/prettier/issues/322#issuecomment-1837193944), there's an "unstable formatting" bug here (different formatting on subsequent saves) with `prettier-plugin-embed` (not present with `prettier-plugin-sql` alone in `.sql` files) when the dollar-quoted string is multiple lines, eg. the code that @innermatrix posted in https://github.com/Sec-ant/prettier-plugin-embed/issues/44:

Original code:

```sql
create function dup (int) returns dup_result as $$ 
  select
      $1,
      cast($1 as text)||' is text'
$$ language sql;
```

First format:

```sql
create function dup (int) returns dup_result as $$ 
      select
          $1,
          cast($1 as text)||' is text'
    $$ language sql;
```

Second format:

```sql
create function dup (int) returns dup_result as $$ 
            select
                $1,
                cast($1 as text)||' is text'
        $$ language sql;
```

https://github.com/Sec-ant/prettier-plugin-embed/assets/1935696/92c770fb-f15c-46d9-b39b-1ba90acd2074

Config:

```js
import { postgresql } from 'sql-formatter';

/** @type {import('prettier').Config} */
const prettierConfig = {
  plugins: [
    'prettier-plugin-embed',
    'prettier-plugin-sql',
  ],
  singleQuote: true,
  trailingComma: 'all',
};

/** @type {import('prettier-plugin-embed').PrettierPluginEmbedOptions} */
const prettierPluginEmbedConfig = {
  embeddedSqlIdentifiers: ['sql'],
};

/** @type {import('prettier-plugin-sql').SqlBaseOptions} */
const prettierPluginSqlConfig = {
  // https://github.com/un-ts/prettier/issues/322#issuecomment-1837193944
  dialect: JSON.stringify(postgresql),

  expressionWidth: 8,
};

const config = {
  ...prettierConfig,
  ...prettierPluginEmbedConfig,
  ...prettierPluginSqlConfig,
};

export default config;

```

**Comment by karlhorky** [comment] 2023-12-04 14:33
@Sec-ant I've tracked it down to the `textToDoc()` function call in the SQL embedder:

https://github.com/Sec-ant/prettier-plugin-embed/blob/85e9c3183fa0ca5be9a2c99e596ec62f69177050/src/embedded/sql/embedder.ts#L45-L48

Here the `text` looks like this (note the 2 leading spaces on the first line):

```sql
  create function dup (int) returns dup_result as $$ 
    select
        $1,
        cast($1 as text)||' is text'
  $$ language sql;
```

Then `doc` looks like this afterwards (note the \*missing\* 2 leading spaces on the first line):

```sql
create function dup (int) returns dup_result as $$ 
    select
        $1,
        cast($1 as text)||' is text'
  $$ language sql;
```

You can also see this discrepancy when adding leading spaces on [the SQL Formatter demo](https://sql-formatter-org.github.io/sql-formatter/)

cc @nene I guess this is a small bug in `sql-formatter` maybe it would be an idea to:

1. for queries with `$$`, format the rest of the string with indentation matching the delta from the first line (in this example, `-2`)
2. avoid any type of indentation with any queries including `$$`

Then Prettier indents the template string as normal, and adds the extra spaces, pushing the code in each successive format further over to the right.

**Comment by karlhorky** [comment] 2023-12-04 14:33
## Workaround

My current workaround for `prettier-plugin-embed` looks like this:

```ts
import dedent from 'dedent';

// ...

  const doc = await textToDoc(dedent(text), {
    ...options,
    parser: "sql",
  });
```

**Comment by karlhorky** [comment] 2023-12-04 15:06
I just tried it, and it's not working.

[`dedent`](https://www.npmjs.com/package/dedent) operates on every line, not just the start and end

**Comment by nene** [comment] 2023-12-04 15:54
I think there is a fundamental incompatibility here because sql-formatter outputs it's result as plain string, indentation of which can't be further adjusted by the Prettier layout engine.

One can't simply e.g. remove or add leading whitespace to all lines as the whitespace can be significant e.g. it appears inside a string.

One possible workaround would be to add some sort of `minIndent: number` option to SQL Formatter, allowing one to specify a minimum indentation level.

**Comment by Sec-ant** [comment] 2023-12-04 16:25
I just applied the patch provided by @karlhorky and reproduced this issue.

Several thoughts here:

1. `sql-formatter` will trim the whitespace during formatting, that's why the current behavior seems agree with `trimmedText` and thus not related to this issue. Though I still think I should refactor this piece of code to use `trimmedText` in all other places.

2. I can get it that [`sql-formatter` doesn't touch the rest of `$$` strings (by design)](https://github.com/sql-formatter-org/sql-formatter/issues/183#issuecomment-1116363644), and I agree with [this argument](https://github.com/sql-formatter-org/sql-formatter/issues/682#issuecomment-1838906664):

    > The whitespace inside strings is assumed to be significant and therefore not modified. For example one could write a python script inside $$-quoted string. Whitespace in Python is significant and modifying it would lead to broken code.

3. I've thought about there may be circumstances where multiline indentation are not desired, so there's an option called [`noEmbeddedMultiLineIndentation`](https://github.com/Sec-ant/prettier-plugin-embed#language-agnostic-options). If you add this setting `noEmbeddedMultiLineIndentation: ["sql"]` to the options, it seems that the formatting behavior becomes stable @karlhorky. Although this will discard indentation for all lines, not only those inside `$$`.

4. As for what @nene mentioned in https://github.com/Sec-ant/prettier-plugin-embed/issues/45#issuecomment-1838939567. 

    > I think there is a fundamental incompatibility here because sql-formatter outputs it's result as plain string, indentation of which can't be further adjusted by the Prettier layout engine.

    This is known, so [all string literal new lines are splitted and marked as Prettier layout new lines](https://github.com/Sec-ant/prettier-plugin-embed/blob/85e9c3183fa0ca5be9a2c99e596ec62f69177050/src/embedded/sql/embedder.ts#L63-L65) inside this plugin. The proper way would be only split those new lines that are not considered as significant ones and this should be handled by the sql plugin/parser. I think the root cause here is that we're not actually using the Prettier layout engine with `sql-formatter`. Instead of inventing workarounds for these quirks, maybe we can wait for `prettier-plugin-sql-cst` to properly handle this?

**Comment by karlhorky** [comment] 2023-12-04 17:23
Since users have the ability of using either `noEmbeddedMultiLineIndentation` or `prettier-ignore` as escape hatches for whitespace-sensitive strings (which are probably pretty uncommon anyway), I would suggest that `dedent` or similar should be used by default on the `text`.

**Comment by Sec-ant** [comment] 2023-12-12 02:27
@karlhorky Would you mind testing the package in #50 to see if it works?

**Comment by karlhorky** [comment] 2023-12-12 14:11
Sure, will answer over in #50.

**Comment by Sec-ant** [comment] 2023-12-12 15:21
The workaround mentioned in https://github.com/Sec-ant/prettier-plugin-embed/issues/45#issuecomment-1838761862 is added in #50 and released in [https://github.com/Sec-ant/prettier-plugin-embed/releases/tag/v0.3.2](v0.3.2). Thanks @karlhorky. I'm closing this issue now.

**Closed by Sec-ant** 2023-12-12 15:21 UTC

**Comment by karlhorky** [comment] 2023-12-12 16:02
I'll upgrade our projects to `prettier-plugin-embed@0.3.2` and keep an eye on any regressions that appear, but I'm guessing it should be ok - I already tested this with formatting on a medium codebase.
